[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_URL,SUPABASE_ANON_KEY,SUPABASE_URL"
